# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1feCkdIYr8e1V5KIzxxooJr5o2bRK4R4p
"""

import nltk
import random
import numpy as np
import json
import pickle
import os
import traceback
import re
from nltk.stem import WordNetLemmatizer
from tensorflow.keras.models import load_model
lemmatizer=WordNetLemmatizer()

with open('intents.json') as json_file:
    intents = json.load(json_file)

words=pickle.load(open('words.pkl','rb'))
classes=pickle.load(open('classes.pkl','rb'))

# Load model with graceful failure handling
model = None
_model_load_error = None
try:
  if os.path.exists('chatbotmodel.h5'):
    model = load_model('chatbotmodel.h5')
  else:
    _model_load_error = "Model file 'chatbotmodel.h5' not found."
except Exception as _e:
  _model_load_error = f"Failed to load model: {_e}"
  # Print detailed traceback to console for developers
  traceback.print_exc()

def _ensure_nltk():
  try:
    nltk.data.find('tokenizers/punkt')
  except LookupError:
    try:
      nltk.download('punkt', quiet=True)
    except Exception:
      pass
  try:
    nltk.data.find('corpora/wordnet')
  except LookupError:
    try:
      nltk.download('wordnet', quiet=True)
      nltk.download('omw-1.4', quiet=True)
    except Exception:
      pass

def _normalize_text(text: str) -> str:
  if not isinstance(text, str):
    return ""
  text = text.lower()
  text = re.sub(r"[^a-z0-9\s]", " ", text)
  text = re.sub(r"\s+", " ", text).strip()
  return text

def _tokenize_simple(text: str) -> set:
  _ensure_nltk()
  normalized = _normalize_text(text)
  if not normalized:
    return set()
  try:
    # Use simple split to avoid dependency on punkt for fallback
    return set(normalized.split())
  except Exception:
    return set(normalized.split())

def clean_up_sentence(sentence):
  """Tokenize and lemmatize input sentence, ensuring NLTK data is available."""
  try:
    _ensure_nltk()
    sentence_words=nltk.word_tokenize(sentence.lower())
  except LookupError:
    # Ensure required NLTK data is present at runtime (first run experience)
    try:
      _ensure_nltk()
    except Exception:
      pass
    sentence_words=nltk.word_tokenize(sentence.lower())
  sentence_words=[lemmatizer.lemmatize(word) for word in sentence_words]
  return sentence_words

def bag_of_words(sentence):
  sentence_words=clean_up_sentence(sentence)
  bag=[0]*len(words)
  for w in sentence_words:
    for i,word in enumerate(words):
      if word == w:
        bag[i]=1
  return np.array(bag)

def predict_class(sentence):
  if model is None:
    return []
  bow=bag_of_words(sentence)
  res=model.predict(np.array([bow]))[0]
  ERROR_THRESHOLD=0.25
  results=[[i,r] for i,r in enumerate(res) if r> ERROR_THRESHOLD]

  results.sort(key=lambda x:x[1],reverse=True)
  return_list=[]
  for r in results:
    return_list.append({'intent': classes[r[0]],'probability':str(r[1])})
  return return_list

def get_response(intents_list,intents_json):
  if not intents_list:
    return "I'm not sure I understand. Could you rephrase?"
  tag=intents_list[0]['intent']
  list_of_intents=intents_json['intents']
  for i in list_of_intents:
    if i['tag']==tag and i.get('responses'):
      return random.choice(i['responses'])
  return "I'm not sure I understand. Could you rephrase?"

def chat(message: str) -> str:
  """Return chatbot response for a given user message."""
  if not message or not message.strip():
    return "Please enter a message."
  try:
    # If model failed to load, use a simple keyword-based fallback using intents patterns
    if model is None:
      if _model_load_error:
        # Log the reason once for developers
        print(f"[MedBot] Model unavailable: {_model_load_error}")
      # Token-overlap (Jaccard) fallback against patterns
      msg_tokens = _tokenize_simple(message)
      best_score = 0.0
      best_responses = None
      for intent in intents.get('intents', []):
        patterns = intent.get('patterns') or []
        for pattern in patterns:
          if not isinstance(pattern, str):
            continue
          pat_tokens = _tokenize_simple(pattern)
          if not pat_tokens:
            continue
          inter = len(msg_tokens & pat_tokens)
          union = len(msg_tokens | pat_tokens) or 1
          score = inter / union
          if score > best_score:
            best_score = score
            best_responses = intent.get('responses') or []
      if best_responses and best_score >= 0.2:  # modest threshold
        return random.choice(best_responses)
      return "I'm not fully set up yet. Please try a simple greeting or ensure the model is installed."

    intents_pred = predict_class(message)
    if not intents_pred:
      return "I'm not sure I understand. Could you rephrase?"
    response = get_response(intents_pred, intents)
    return response
  except Exception as e:
    # Log details to console for debugging, but return a user-friendly message
    print("[MedBot] Unexpected error:", repr(e))
    traceback.print_exc()
    return "I'm sorry, I ran into an error generating a response."

if __name__ == '__main__':
  print("GO! BOT IS RUNNING")
  while True:
    message=input("")
    ints=predict_class(message)
    res=get_response(ints,intents) if ints else "I'm not sure I understand. Could you rephrase?"
    print(res)